name: Deployment On AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build And Push
        run: |

      - name: Deploy On AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.233.195.161
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          debug: true
          script: |
            cd /home/ubuntu/cc26-p-products-store
            git pull
            docker build -t my-app-image .
            docker run -d --name my-app -p 5173:5173 my-app-image
